// Generated by gencpp from file bebop_brain_drone_race/Error.msg
// DO NOT EDIT!


#ifndef BEBOP_BRAIN_DRONE_RACE_MESSAGE_ERROR_H
#define BEBOP_BRAIN_DRONE_RACE_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bebop_brain_drone_race
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : y(0.0)
    , z(0.0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::bebop_brain_drone_race::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bebop_brain_drone_race::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::bebop_brain_drone_race::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::bebop_brain_drone_race::Error > ErrorPtr;
typedef boost::shared_ptr< ::bebop_brain_drone_race::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bebop_brain_drone_race::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bebop_brain_drone_race::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bebop_brain_drone_race

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bebop_brain_drone_race': ['/home/ejsawyers/BDR/src/bebop_brain_drone_race/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bebop_brain_drone_race::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bebop_brain_drone_race::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bebop_brain_drone_race::Error_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "620052061599731a9bd2b8c4e407c781";
  }

  static const char* value(const ::bebop_brain_drone_race::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x620052061599731aULL;
  static const uint64_t static_value2 = 0x9bd2b8c4e407c781ULL;
};

template<class ContainerAllocator>
struct DataType< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bebop_brain_drone_race/Error";
  }

  static const char* value(const ::bebop_brain_drone_race::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::bebop_brain_drone_race::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bebop_brain_drone_race::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bebop_brain_drone_race::Error_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEBOP_BRAIN_DRONE_RACE_MESSAGE_ERROR_H
